backend:
  name: github
  repo: sajclarke/productsbyos

media_folder: assets/img/uploads

collections:
  - name: post
    label: Post
    folder: posts
    extension: json
    widget: 'list'
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: text }
      - { name: photo, label: Photo, widget: image }
  - name: staff
    label: Staff
    folder: staff
    extension: json
    widget: 'list'
    create: true
    fields:
      - { name: role, label: Role }
      - { name: fullname, label: FullName, widget: text }
      - { name: photo, label: Photo, widget: image }
  - name: products
    label: Products
    folder: products
    extension: json
    widget: 'list'
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Description, widget: text }
      - { name: photo, label: Photo, widget: image }
